export type StylesPrefixesKeys = keyof typeof stylesPrefixes;
export type StylesPrefixes = Record<StylesPrefixesKeys, string | string[]>;
export type StylePrefixType = 'number' | 'string' | 'color';

const stylesPrefixes = {
  mx: ['marginLeft', 'marginRight'],
  my: ['marginTop', 'marginBottom'],
  'm-inline': ['marginInline', 'marginHorizontal'],
  'm-inline-end': ['marginInlineEnd', 'marginEnd'],
  'm-inline-start': ['marginInlineStart', 'marginStart'],
  'm-block': ['marginBlock', 'marginVertical'],
  'm-block-end': ['marginBlockEnd', 'marginBottom'],
  'm-block-start': ['marginBlockStart', 'marginTop'],
  px: ['paddingLeft', 'paddingRight'],
  py: ['paddingTop', 'paddingBottom'],
  'p-inline': ['paddingInline', 'paddingHorizontal'],
  'p-inline-end': ['paddingInlineEnd', 'paddingEnd'],
  'p-inline-start': ['paddingInlineStart', 'paddingStart'],
  'p-block': ['paddingBlock', 'paddingVertical'],
  'p-block-end': ['paddingBlockEnd', 'paddingBottom'],
  'p-block-start': ['paddingBlockStart', 'paddingTop'],
  h: 'height',
  'max-h': 'maxHeight',
  'min-h': 'minHeight',
  w: 'width',
  'max-w': 'maxWidth',
  'min-w': 'minWidth',
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  me: 'marginEnd',
  ms: 'marginStart',
  mbe: ['marginBlockEnd', 'marginBottom'],
  mbs: ['marginBlockStart', 'marginTop'],
  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  pe: 'paddingEnd',
  ps: 'paddingStart',
  pbe: ['paddingBlockEnd', 'paddingBottom'],
  pbs: ['paddingBlockStart', 'paddingTop'],
  flex: 'flex',
  'border-radius': 'borderRadius',
  'border-radius-tl': 'borderTopLeftRadius',
  'border-radius-tr': 'borderTopRightRadius',
  'border-radius-br': 'borderBottomRightRadius',
  'border-radius-bl': 'borderBottomLeftRadius',
  'border-radius-be': 'borderBottomEndRadius',
  'border-radius-bs': 'borderBottomStartRadius',
  'border-radius-ee': 'borderEndEndRadius',
  'border-radius-es': 'borderEndStartRadius',
  'border-radius-se': 'borderStartEndRadius',
  'border-radius-ss': 'borderStartStartRadius',
  'border-radius-te': 'borderTopEndRadius',
  'border-radius-ts': 'borderTopStartRadius',
  'border-b': 'borderBottomWidth',
  'border-e': 'borderEndWidth',
  'border-l': 'borderLeftWidth',
  'border-r': 'borderRightWidth',
  'border-s': 'borderStartWidth',
  'border-t': 'borderTopWidth',
  'border-w': 'borderWidth',
  border: 'borderColor',
  'border-block-color': [
    'borderBlockColor',
    'borderTopColor',
    'borderBottomColor',
  ],
  'border-block-end-color': ['borderBlockEndColor', 'borderBottomColor'],
  'border-block-start-color': ['borderBlockStartColor', 'borderTopColor'],
  'border-b-color': 'borderBottomColor',
  'border-be-color': ['borderBlockEndColor', 'borderBottomColor'],
  'border-e-color': 'borderEndColor',
  'border-l-color': 'borderLeftColor',
  'border-r-color': 'borderRightColor',
  'border-s-color': 'borderStartColor',
  'border-bs-color': ['borderBlockStartColor', 'borderTopColor'],
  'border-t-color': 'borderTopColor',
  bg: 'backgroundColor',
  color: 'color',
  'font-size': 'fontSize',
  'font-weight': 'fontWeight',
  'line-height': 'lineHeight',
  'flex-shrink': 'flexShrink',
  text: 'color',
  'flex-grow': 'flexGrow',
  aspect: 'aspectRatio',
  z: 'zIndex',
  l: 'left',
  r: 'right',
  t: 'top',
  b: 'bottom',
  opacity: 'opacity',
  'gap-x': 'columnGap',
  'gap-y': 'rowGap',
  gap: 'gap',
  elevation: 'elevation',
  end: 'end',
  basis: 'flexBasis',
  font: 'fontFamily',
  tracking: 'letterSpacing',
  outline: 'outlineColor',
  'outline-offset': 'outlineOffset',
  'outline-w': 'outlineWidth',
  overlay: 'overlayColor',
  shadow: 'shadowColor',
  start: 'start',
  decoration: 'textDecorationColor',
  'text-shadow': 'textShadowColor',
  'text-shadow-radius': 'textShadowRadius',
  'tint': 'tintColor'
} as const;

const stylePrefixTypes: Partial<Record<StylesPrefixesKeys, StylePrefixType>> = {
  border: 'color',
  'border-block-color': 'color',
  'border-block-end-color': 'color',
  'border-block-start-color': 'color',
  'border-b-color': 'color',
  'border-be-color': 'color',
  'border-e-color': 'color',
  'border-l-color': 'color',
  'border-r-color': 'color',
  'border-s-color': 'color',
  'border-bs-color': 'color',
  'border-t-color': 'color',
  bg: 'color',
  color: 'color',
  text: 'color',
  outline: 'color',
  overlay: 'color',
  shadow: 'color',
  decoration: 'color',
  'text-shadow': 'color',
  tint: 'color',
  font: 'string',
};

export const getStylePrefixType = (prefix: StylesPrefixesKeys): StylePrefixType =>
  stylePrefixTypes[prefix] ?? 'number';

export default stylesPrefixes;
