export type StylesPrefixesKeys = keyof typeof stylesPrefixes;
export type StylesPrefixes = Record<StylesPrefixesKeys, string | string[]>;

const stylesPrefixes = {
  mx: ['marginLeft', 'marginRight'],
  my: ['marginTop', 'marginBottom'],
  px: ['paddingLeft', 'paddingRight'],
  py: ['paddingTop', 'paddingBottom'],
  h: 'height',
  'max-h': 'maxHeight',
  'min-h': 'minHeight',
  w: 'width',
  'max-w': 'maxWidth',
  'min-w': 'minWidth',
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  me: 'marginEnd',
  ms: 'marginStart',
  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  pe: 'paddingEnd',
  ps: 'paddingStart',
  flex: 'flex',
  'border-radius': 'borderRadius',
  'border-radius-tl': 'borderTopLeftRadius',
  'border-radius-tr': 'borderTopRightRadius',
  'border-radius-br': 'borderBottomRightRadius',
  'border-radius-bl': 'borderBottomLeftRadius',
  'border-radius-be': 'borderBottomEndRadius',
  'border-radius-bs': 'borderBottomStartRadius',
  'border-radius-ee': 'borderEndEndRadius',
  'border-radius-es': 'borderEndStartRadius',
  'border-radius-se': 'borderStartEndRadius',
  'border-radius-ss': 'borderStartStartRadius',
  'border-radius-te': 'borderTopEndRadius',
  'border-radius-ts': 'borderTopStartRadius',
  'border-b': 'borderBottomWidth',
  'border-e': 'borderEndWidth',
  'border-l': 'borderLeftWidth',
  'border-r': 'borderRightWidth',
  'border-s': 'borderStartWidth',
  'border-t': 'borderTopWidth',
  'border-w': 'borderWidth',
  border: 'borderColor',
  'border-b-color': 'borderBottomColor',
  'border-e-color': 'borderEndColor',
  'border-l-color': 'borderLeftColor',
  'border-r-color': 'borderRightColor',
  'border-s-color': 'borderStartColor',
  'border-t-color': 'borderTopColor',
  bg: 'backgroundColor',
  color: 'color',
  'font-size': 'fontSize',
  'font-weight': 'fontWeight',
  'line-height': 'lineHeight',
  'flex-shrink': 'flexShrink',
  text: 'color',
  'flex-grow': 'flexGrow',
  aspect: 'aspectRatio',
  z: 'zIndex',
  l: 'left',
  r: 'right',
  t: 'top',
  b: 'bottom',
  opacity: 'opacity',
  'gap-x': 'columnGap',
  'gap-y': 'rowGap',
  gap: 'gap',
  elevation: 'elevation',
  end: 'end',
  basis: 'flexBasis',
  font: 'fontFamily',
  tracking: 'letterSpacing',
  outline: 'outlineColor',
  'outline-offset': 'outlineOffset',
  'outline-w': 'outlineWidth',
  overlay: 'overlayColor',
  shadow: 'shadowColor',
  start: 'start',
  decoration: 'textDecorationColor',
  'text-shadow': 'textShadowColor',
  'text-shadow-radius': 'textShadowRadius',
  'tint': 'tintColor'
} as const;

export default stylesPrefixes;
